url: http://www.runforlearning.com

org_name: Run For Learning

name: Run For Learning 5K Run/Walk and Kids Fun Run

short_name: 5K Run/Walk and Kids Fun Run

description: 5K Run/Walk and Kids Fun Run to raise funds for two Grayslake pre-schools

author_email: webmaster@grayslake-coop.com

event_date: "September 19th, 2015"

event_location: "Downtown Grayslake, IL"

registration_vendor_url: "www.signmeup.com/101582"

registration_link: '<a href="http://www.signmeup.com/101582" class="btn btn-danger btn-lg" disabled="disabled" target="_blank">Register</a>'

sponsor_link: '<a href ="/sponsor.html" class="btn btn-success btn-lg">Become a Sponsor</a>'

facebook_url: 'https://www.facebook.com/runforlearning5k'

contact_email: 'runforlearning@gmail.com'

contact_phone: '(224) 419-4023'

sponsorship_form_url: 'assets/files/rfl_5k_sponsorship_form_v3.pdf'

logo_image: '<img src="assets/images/run_for_learning_logo_2015.png" alt="Run for Learning logo"/>'

2014_logo_image: '<img src="assets/images/run_for_learning_logo_2014.jpg" alt="Run for Learning logo"/>'

gcns_url: 'http://www.grayslake-coop.com/'

gcns_logo_url: 'assets/images/gcns_logo.jpg'

gloryland_url: 'http://www.glorylandpreschool.com/'

gloryland_logo_url: 'assets/images/gloryland_logo.jpg'

westlake_url: 'http://westlakechristian.org/'

westlake_logo_url: 'assets/images/westlakechristian_logo.jpg'

peppermint_url: 'http://peppermintstickcc.com'

peppermint_logo_url: 'assets/images/peppermint_stick_logo.jpg'

tt_url: 'http://www.wildwoodpc.net/preschool/'

tt_logo_url: 'assets/images/tiny_treasures_logo.jpg'

race_results_5k_2014: '<a href="http://racetime.info/wp-content/uploads/2014/09/Run-For-Learning-5K-Overall-Results.htm" title="Run for Learning 5K 2014 Race Results" class="btn btn-success btn-lg" target="_blank">5K race results</a>'

race_results_1k_2014: '<a href="http://racetime.info/wp-content/uploads/2014/09/Run-For-Learning-1K-Youth-Overall-Results.htm" title="Run for Learning 1K 2014 Race Results" class="btn btn-success btn-lg" target="_blank">1K race results</a>'

exclude: [README.md, tags, vendor]

